#include "PinyinSample.hpp"

WCDB_CPP_ORM_IMPLEMENTATION_BEGIN(PinyinSample)
WCDB_CPP_SYNTHESIZE(content)
WCDB_CPP_VIRTUAL_TABLE_MODULE(WCDB::Module::FTS5)
WCDB_CPP_VIRTUAL_TABLE_TOKENIZE(WCDB::BuiltinTokenizer::Pinyin)
WCDB_CPP_ORM_IMPLEMENTATION_END
